apiVersion: v1
kind: Pod
metadata:
  name: ray-head
  labels:
    app: ray-head
spec:
  containers:
  - name: ray-head
    image: docker.io/charleeagni/ray-node:latest
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - containerPort: 6379
    - containerPort: 12345
    - containerPort: 8888
    args: ["--head", "--redis-port", "6379", "--object-manager-port", "12345", "--block"]
