apiVersion: v1
kind: Service
metadata:
  name: ray-head-service
  labels:
    app: ray-head
spec:
  type: NodePort
  selector: 
    app: ray-head
  ports:
  - port: 8888
    name: jupyter
    protocol: TCP
    nodePort: 32767
  - port: 6379
    name: redis
    protocol: TCP
    nodePort: 31379
  - port: 12345
    name: ray
    protocol: TCP
    nodePort: 31234
