apiVersion: v1
kind: Pod
metadata:
  name: ray-worker
  labels:
    app: ray-head
spec:
  containers:
  - name: ray-head
    image: docker.io/charleeagni/ray-node:latest
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - containerPort: 6379
    - containerPort: 12345
    args: ["--redis-address", "10.4.0.6:6379", "--object-manager-port", "12345", "--block"]
